// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using galli.mingucci._5i.Progetto_E_Commerce.Data;

#nullable disable

namespace galli.mingucci._5i.Progetto_E_Commerce.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20240412151509_Prova1 ECommerce")]
    partial class Prova1ECommerce
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PrenotationTotalBill")
                        .HasColumnType("REAL");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<int>("_Sex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Password");

                    b.HasIndex("LoginPassword");

                    b.HasIndex("PrenotationTotalBill");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Bike", b =>
                {
                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clutch")
                        .HasColumnType("TEXT");

                    b.Property<string>("CylinderDisposition")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cylinders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CylindersConfiguration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Displacement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Distribution")
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PrenotationTotalBill")
                        .HasColumnType("REAL");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ProductionYear")
                        .HasColumnType("TEXT");

                    b.Property<string>("Refrigeration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SetUp")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartUp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Strokes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValvesNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Model");

                    b.HasIndex("PrenotationTotalBill");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Circuit", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeModel")
                        .HasColumnType("TEXT");

                    b.Property<int>("CircuitLenght")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurvesNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Editions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Laps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceLenght")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Site")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipology")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("BikeModel");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Login", b =>
                {
                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Password");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Prenotation", b =>
                {
                    b.Property<double>("TotalBill")
                        .HasColumnType("REAL");

                    b.Property<string>("ChoosenCircuit")
                        .HasColumnType("TEXT");

                    b.Property<double>("CircuitPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursPrenoted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PTotMoto")
                        .HasColumnType("REAL");

                    b.Property<int>("PeopleNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("TotalBill");

                    b.ToTable("Prenotations");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.ApplicationUser", b =>
                {
                    b.HasOne("galli.mingucci._5i.Progetto_E_Commerce.Data.Login", null)
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("LoginPassword");

                    b.HasOne("galli.mingucci._5i.Progetto_E_Commerce.Data.Prenotation", null)
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("PrenotationTotalBill");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Bike", b =>
                {
                    b.HasOne("galli.mingucci._5i.Progetto_E_Commerce.Data.Prenotation", null)
                        .WithMany("ChoosenBikes")
                        .HasForeignKey("PrenotationTotalBill");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Circuit", b =>
                {
                    b.HasOne("galli.mingucci._5i.Progetto_E_Commerce.Data.Bike", null)
                        .WithMany("Circuits")
                        .HasForeignKey("BikeModel");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Bike", b =>
                {
                    b.Navigation("Circuits");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Login", b =>
                {
                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("galli.mingucci._5i.Progetto_E_Commerce.Data.Prenotation", b =>
                {
                    b.Navigation("ApplicationUsers");

                    b.Navigation("ChoosenBikes");
                });
#pragma warning restore 612, 618
        }
    }
}
